### PR TITLE
archlinux: enable munin-cron as systemd timer

### PR DESCRIPTION
**Pull request by jamesp9**

### CODE REVIEW

**Comment by gravyboat** [comment]
Should the cron timer be part of the init? Is it critical to Arch? If not I'd prefer to have it in a different file so people don't have to use it if they don't want to.

**Comment by jamesp9** [comment]
Arch doesn't seem to enable `munin-cron` by default, then further gives the choice of using either crontab or a systemd timer.
A seperate file would make sense, is another salt state e.g. "munin.master.munin-cron" acceptable. ?

**Comment by gravyboat** [comment]
@jamesp9 Yeah that would be great!

**Comment by gravyboat** [comment]
@jamesp9 Are you going to pull this into a separate file? I see you added it to the readme.

**Comment by jamesp9** [comment]
@gravyboat Yes, this is the plan. Got busy and didn't quite get to it yet.

**Comment by gravyboat** [comment]
@jamesp9 Sounds good, just comment back when you're ready to go.

**Comment by jamesp9** [comment]
@gravyboat The commit for this `munin-cron` addtion has been fixed up. Could please review.

**Comment by gravyboat** [comment]
Looks good to me @jamesp9! Thanks!

**Pull request merged**
